#ifndef WARSHIPS_AIRPLANES_DLL_GLOBAL_H
#define WARSHIPS_AIRPLANES_DLL_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(WARSHIPS_AIRPLANES_DLL_LIBRARY)
#  define WARSHIPS_AIRPLANES_DLLSHARED_EXPORT Q_DECL_EXPORT
#else
#  define WARSHIPS_AIRPLANES_DLLSHARED_EXPORT Q_DECL_IMPORT
#endif

#endif // WARSHIPS_AIRPLANES_DLL_GLOBAL_H
